#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: calculator-deployment
#  labels:
#    app: calculator
#spec:
#  replicas: 1
#  strategy:
#    type: RollingUpdate
#    rollingUpdate:
#      maxUnavailable: 50%
#      maxSurge: 0
#  selector:
#    matchLabels:
#      app: calculator
#  template:
#    metadata:
#      labels:
#        app: calculator
#    spec:
#      containers:
#        - name: calculator
#          image: quantumempress/calc:caching
#          ports:
#            - containerPort: 8080

apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-deployment
  labels:
    app: calculator
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 0
  selector:
    matchLabels:
      app: calculator
  template:
    metadata:
      labels:
        app: calculator
    spec:
      containers:
        - name: calculator
          image: quantumempress/calculator:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
